### ISSUE TITLE
about h265 video play details

### ISSUE THREAD

**Issue by fingerx** [adrenak/GPUVideoPlayer#6]
i saw "GPUVideoPlayer was tested with an 800mb 8192x4096 30FPS H265 MP4 video file. Loading took 195 ms. Video playback was at 30FPS with Unity's framerate at 60." this is great.Can you provide detailed information on this video or download link? Because I tested a 4k and 8k video playback with color errors and not smooth (the original project and my own compilation are the same). I have to run the system win10 64bit, the graphics card is amd w8100, e5-2630, I am not sure if it is my hardware problem.

**Comment by fingerx** [comment]
i am installed **HEVC Video Extensions from Device Manufacturer** in ms store. using ms defualt video player is smooth but use plugin is not good.

**Comment by adrenak** [comment]
Not sure what the reason is, but I also had HEVC Video Extensions from Device Manufacturer before and had the _same_ issue. Later a client told me I need HEVC Video Extensions which is the one I mentioned above. Purchased that and it started working.

I think that if you play a video check your task manager, you will see under performance that the video decode usage is almost zero. Without HEVC Video Extensions the decoding is happening on the CPU, hence it is slow.

**Comment by fingerx** [comment]
thanks very much . i dont konw why ms need 1$ . unity 2019 support h265 video .
